export const CATEGORY = [
  "Shop",
  "Wine Shop",
  "Wedding",
  "Travel",
  "Transpoters",
  "Training Institute",
  "Sports goods",
  "Sports coach",
  "shopping",
  "buzcafe news",
  "Buzcafe Social",
  "buzcafe pay",
  "anything on hire",
  "apply for loan",
  "auto care",
  "auto mobile",
  "b 2 b",
  "baby care",
  "banquets",
  "bills & recharge",
  "books hotels",
  "train",
  "books",
  "cab car rental",
  "caterers",
  "civil contractor",
  "courier",
  "daily needs",
  "dance & music",
  "florist",
  "educations",
  "pet & pet care",
  "playschool",
  "language classes",
];