export const FeatureShop = [
  '0x58D45F9b7956602291fCF192a7c3bB04cBfeD7bF',
  
]

export const CATEGORY = [
  "Shop",
  "Wine Shop",
  "Wedding",
  "Travel",
  "Transpoters",
  "Training Institute",
  "Sports goods",
  "Sports coach",
  "shopping",
  "buzcafe news",
  "Buzcafe Social",
  "buzcafe pay",
  "anything on hire",
  "apply for loan",
  "auto care",
  "auto mobile",
  "b 2 b",
  "baby care",
  "banquets",
  "bills & recharge",
  "books hotels",
  "train",
  "books",
  "cab car rental",
  "caterers",
  "civil contractor",
  "courier",
  "daily needs",
  "dance & music",
  "florist",
  "educations",
  "pet & pet care",
  "playschool",
  "language classes",
];